import os
import google.generativeai as genai


def configure_gemini(api_key=None):
    # clé par défaut via variable d’environnement
    if api_key is None:
        api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise ValueError("Gemini API key not provided. Set GEMINI_API_KEY.")
    genai.configure(api_key=api_key)


def _call_gemini(prompt: str, api_key=None) -> str:
    configure_gemini(api_key)
    model = genai.GenerativeModel("gemini-2.5-flash")
    response = model.generate_content(prompt)
    return response.text.strip()


def fuse_captions_with_gemini(captions: dict, consensus_caption: str, api_key=None) -> str:
    prompt = (
        "You are an expert image captioning system.\n\n"
        "Here are captions generated by independent vision models:\n"
        + "\n".join([f"- {k}: \"{v}\"" for k, v in captions.items()])
        + f"\n\nConsensus caption (most reliable): \"{consensus_caption}\"\n\n"
        "Your task:\n"
        "- Fuse only consistent information from the captions\n"
        "- Do NOT add new objects or details\n"
        "- Keep it simple, accurate, natural\n"
        "- Output MUST be in ENGLISH ONLY\n"
        "- Output ONLY the final caption\n\n"
        "Final caption:"
    )
    return _call_gemini(prompt, api_key=api_key)


def self_correct_caption(caption: str, api_key=None) -> str:
    prompt = (
        "You are reviewing an image caption:\n\n"
        f"\"{caption}\"\n\n"
        "Check for:\n"
        "- contradictions\n"
        "- repetition\n"
        "- unclear phrasing\n\n"
        "If it's already good, return it unchanged.\n"
        "Otherwise, return a corrected improved version.\n\n"
        "Return ONLY the caption in ENGLISH."
    )
    return _call_gemini(prompt, api_key=api_key)


def fuse_with_tree_of_thoughts(captions: dict, consensus_caption: str, api_key=None) -> list[str]:
    # 2 branches = ToT simple (concise vs slightly descriptive)
    prompts = [
        "Write a concise factual caption (one sentence).",
        "Write a slightly more descriptive caption, still factual (one sentence)."
    ]

    candidates = []
    for p in prompts:
        prompt = (
            f"{p}\n\n"
            "Independent captions:\n"
            + "\n".join([f"- {k}: \"{v}\"" for k, v in captions.items()])
            + f"\n\nConsensus caption: \"{consensus_caption}\"\n\n"
            "Rules:\n"
            "- Do NOT add new objects not supported by the captions\n"
            "- English only\n"
            "- Output only the caption\n\n"
            "Caption:"
        )
        candidates.append(_call_gemini(prompt, api_key=api_key))

    return candidates
